# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Now Interactive LLC
email: mspandit@now-interactive.net
description: > # this means to ignore newlines until "baseurl:"
  Now Interactive LLC employs agile and test-driven development methodologies 
  for extremely rapid delivery of marketing, customer service, and electronic 
  commerce solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.now-interactive.net" # the base hostname & protocol for your site
twitter_username: nwntrctv
github_username:  mspandit

# Build settings
markdown: kramdown
